### ISSUE TITLE
When can the codes be published?

### ISSUE THREAD

**Issue by curiosity654** [ali-chr/ZSL_3D_point_cloud#1]
Hi there, thanks for the project. I'm a student working on point cloud classification and I'm interested in this paper. Do you still have the plan to release the code?

**Comment by ali-chr** [comment]
Hi Sunny,

Thanks for your interest in my work. We are working on a journal version on this work. We will upload on arxiv soon ( maybe at end of this month). We will release all codes too.

Best regards,
Ali

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by curiosity654** [comment]
Thank you for the quick reply! Looking forward to it and best regards.
